sudo: false
language: python
python:
    - '3.6'
install:
    - pip install -U flake8 pipenv setuptools wheel pip
    - pip install -r requirements.txt
before_script:
    - flake8 --ignore=W391 progressbar tests
script:
    - python PlexAniSync.py
