sudo: false
language: python
python:
  - '3.6'
install:
  - pip install -U flake8 pylint pylint-exit
  - pip install -r requirements.txt
before_script:
  - flake8 .
  - pylint PlexAniSync.py TautulliSyncHelper.py plexmodule.py anilist.py || pylint-exit --error-fail --warn-fail $?
script:
  - python PlexAniSync.py
